app.captcha.list[0].filename=captcha1.jpg
app.captcha.list[0].result=1
app.captcha.list[1].filename=captcha2.jpg
app.captcha.list[1].result=0
app.captcha.list[2].filename=captcha3.jpg
app.captcha.list[2].result=2x
app.captcha.list[3].filename=captcha4.jpg
app.captcha.list[3].result=1
app.captcha.list[4].filename=captcha5.jpg
app.captcha.list[4].result=-1
app.captcha.list[5].filename=captcha6.jpg
app.captcha.list[5].result=4
app.captcha.list[6].filename=captcha7.jpg
app.captcha.list[6].result=2
app.captcha.list[7].filename=captcha8.jpg
app.captcha.list[7].result=48
app.captcha.list[8].filename=captcha9.jpg
app.captcha.list[8].result=0
app.captcha.list[9].filename=captcha10.jpg
app.captcha.list[9].result=4
